config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :reconocimientos, except: :new
  get 'members/:member_id/reconocer' => 'reconocimientos#new', as: :reconocer 

  resources :licencias, except: :new
  get 'members/:member_id/licenciar' => 'licencias#new', as: :licenciar
  
  resources :members do
    collection { post :import }
  end
  root 'static_pages#home'
  resources :users
  get '/help',              to: 'static_pages#help'
  get '/login',             to: 'sessions#new'
  post '/login',            to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get '/mensaje/:tipo',     to: 'mensajes#edit', as: 'edit_mensaje'
  patch '/mensaje/:tipo',   to: 'mensajes#update'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= $luis.class %> - <%= $luis.email %>
  </small>
  <nav>
      <ul>
        <li><%= link_to "Ayuda",  help_path %></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid bg-1">
    <div class="row">
      <div class="col-xs-2", style="margin-top:0px;margin-left:0px;margin-right:0px;border:0px;padding:0px;">
        <%= image_tag("logobNotarios.png", size: "80x70", alt: "Colegio de Notarios de Aguascalientes") %>
      </div>
      <div class="col-sm-10">
        <h1 style="font-family:Tahoma;margin-left:50px;border:0px;font-size:28px;">Colegio de Notarios de Aguascalientes</h1>
        <% if logged_in? %>
          <%= link_to "Salir de sesión", logout_path, method: "delete", class: "navbar-right btn btn-xs" %>
          <% if params[:controller] != "static_pages" %>
            <%= link_to "Inicio",root_path, class: "navbar-right btn btn-xs" %>
            <% if params[:action] != "home" %>
              <%= link_to "Anterior",request.referer, class: "navbar-right btn btn-xs" %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to "Iniciar sesión", login_path, class: "navbar-right btn btn-xs" %>
        <% end %>
        
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container-fluid bg-2">
      <%= render 'layouts/header' %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>