config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :reconocimientos, except: :new
  get 'members/:member_id/reconocer' => 'reconocimientos#new', as: :reconocer 

  resources :licencias, except: :new
  get 'members/:member_id/licenciar' => 'licencias#new', as: :licenciar
  
  resources :members do
    collection { post :import }
  end
  root 'static_pages#home'
  resources :users
  get '/help',              to: 'static_pages#help'
  get '/login',             to: 'sessions#new'
  post '/login',            to: 'sessions#create'
  delete '/logout',         to: 'sessions#destroy'
  get '/mensaje/:tipo',     to: 'mensajes#edit', as: 'edit_mensaje'
  patch '/mensaje/:tipo',   to: 'mensajes#update'
end

app/models/member.rb
class Member < ApplicationRecord
  default_scope -> { order(:numero) }
  enum status: { pasivo: 0, activo: 1 }
  before_save :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
                    length: { maximum: 69 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validate :only_one_president_allowed
  has_many :licencias, dependent: :destroy
  has_many :reconocimientos, dependent: :destroy
  # acts_as_birthday :fechaNacimiento

  # validates :numero, uniqueness: 
  # { message: -> (object, data) do 
  #                      ": El número de Notaría #{data[:value]} ya existe. Verifique por favor"
  #                     end
  # }
  # validates :presidente, uniqueness: 
  # { message: -> (object, data) do 
  #                      ": Solamente puede haber un presidente. Verifique por favor"
  #                     end
  # }

  def only_one_president_allowed
    conteo = Member.where(presidente: true).count
    puts "*** Número de presidentes actual: #{conteo}"
    puts "===== Nombre: #{nombre} --> Presidente: #{presidente}"
    if conteo == 1 && presidente
      errors.add(:presidente, ": Solamente puede haber un presidente. Verifique por favor")
    end
    
  end

  def total_service_time
    end_time = revocacion_fiat || Date.today
    inicio_ejercicio ||= Date.today
    return (((end_time - inicio_ejercicio) - licence_time).to_i) / 365
  end

  def self.cumplen
    miembros = Member.activo
    @cumpleaneros = []
    
    # Next block is an example of WHAT DOESN'T WORK
    #  Gem 'birthday' just doesn't work
    # Member.find_birthdays_for(Date.today)
    #        or
    # miembros.each do |miembro|
    #   @cumpleaneros << miembro if  miembro.birthday_today? 
    # end
    # Next code is what did work on version 1
    fecha_hoy = Date.today.to_formatted_s(:short)
    miembros.each do |miembro|
      if miembro.fechaNacimiento.to_formatted_s(:short) == fecha_hoy
        @cumpleaneros << miembro
      end
    end
    return @cumpleaneros
  end
  
  # Este metodo de clase se utiliza así: Member.emergencia(Date.yesterday)
  # Es importante mandar una fecha como argumento
  # Se puede usar en la consola de Heroku
  def self.emergencia(fecha)
    miembros = Member.activo
    cumpleas = []

    birth_date = fecha.to_formatted_s(:short)
    miembros.each do |miembro|
      if miembro.fechaNacimiento.to_formatted_s(:short) == birth_date
        cumpleas << miembro
      end
    end

    if cumpleas.any?
      members = Member.activo
      admin = User.first
      presi = Member.find_by(presidente: true)
      notiMSG = Mensaje.find_by(tipo: 'notificación').texto
      cumpMSG = Mensaje.find_by(tipo: 'cumpleaños').texto
      cumpleas.each do |cumplea|
        MemberMailer.cumple(cumplea, presi, cumpMSG, admin.email).deliver_now
        notifica = members.select { |item| item != cumplea }
        notifica.each do |noti|
          MemberMailer.notifica_cumple(cumplea, noti, presi, notiMSG).deliver_now
        end
        MemberMailer.notifica_cumple(cumplea, admin, presi, notiMSG).deliver_now
      end
    end
      
  end
  

  # Do the birthay notifications
  def self.aniversarios
    cumpleas = Member.cumplen
    if cumpleas.any?
      members = Member.activo
      admin = User.first
      presi = Member.find_by(presidente: true)
      notiMSG = Mensaje.find_by(tipo: 'notificación').texto
      cumpMSG = Mensaje.find_by(tipo: 'cumpleaños').texto
      cumpleas.each do |cumplea|
        MemberMailer.cumple(cumplea, presi, cumpMSG, admin.email).deliver_now
        notifica = members.select { |item| item != cumplea }
        notifica.each do |noti|
          MemberMailer.notifica_cumple(cumplea, noti, presi, notiMSG).deliver_now
        end
        MemberMailer.notifica_cumple(cumplea, admin, presi, notiMSG).deliver_now
      end
    end

  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      member = find_by_id(row["id"]) || new
      member.attributes = row.to_hash
      member.save!
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |member|
        csv << member.attributes.values_at(*column_names)
      end
    end
  end

  private

    # Converts email to lowercase
    def downcase_email
      email.downcase!
    end

    def licence_time
      total_time = 0
      self.licencias.each do |l|
        total_time += (l.final - l.inicio).to_i
      end
      return total_time
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
    respond_to do |format|
      format.html
      format.csv { send_data @members.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @licencias = @member.licencias
    @reconocimientos = @member.reconocimientos
  end

  # POST /members/import
  def import
    Member.import(params[:file])
    flash[:success] = 'Se ha importado exitosamente el archivo de Notarios a la base de datos.'
    redirect_to members_path
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

      if @member.save
        flash[:success] = "Se agregó exitosamente el registro del Notario."
        redirect_to members_url
      else
        render :new
      end

  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
      if @member.update(member_params)
        flash[:success] = "Se actualizó exitosamente el registro del Notario."
        redirect_to members_url
      else
        render :edit
      end

  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    flash[:success] = "Se eliminó exitosamente el registro del Notario."
    redirect_to members_url

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:numero, :nombre, :email, :fechaNacimiento, :presidente, :fiat_supernumerario, :fiat_notario_titular, :asamblea_aceptacion, :inicio_ejercicio, :revocacion_fiat, :motivo_revocacion, :status)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

  <div class="form-group row">
    <%= f.label :numero, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-2">
      <%= f.number_field :numero, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :nombre, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :nombre, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
      <%= f.label "Tipo de membresía", class: "col-sm-4 form-control-label" %>
      <div class="col-sm-2">
        <%= f.label :status, "Activo" %>
        <%= f.radio_button :status, 'activo' %>
        <%= f.label :status, "Pasivo" %>
        <%= f.radio_button :status, 'pasivo' %>
      </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>

    <div class="form-group row">
      <%= f.label :presidente, class: "col-sm-4 form-control-label" %>
      <div class="col-sm-2">
        <%= f.check_box :presidente, class: "form-control" %>
      </div>
    </div>

  <div class="form-group row">
    <%= f.label :fechaNacimiento, "Fecha de Nacimiento", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4">
      <%= f.date_select :fechaNacimiento, discard_year: true, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :fiat_supernumerario, "Fecha de Fiat Supernumerario", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4" >
      <%= f.date_field :fiat_supernumerario, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :fiat_notario_titular, "Fecha de Fiat Notario Titular", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :fiat_notario_titular, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :asamblea_aceptacion, "Fecha de Asamblea de Aceptación", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :asamblea_aceptacion, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :inicio_ejercicio, "Fecha de Inicio de Ejercicio", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :inicio_ejercicio, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :revocacion_fiat, "Fecha de Revocación de Fiat", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-4">
      <%= f.date_field :revocacion_fiat, class: "form-control form-fecha" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :motivo_revocacion, "Motivo de la Revocación", class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :motivo_revocacion, class: "form-control" %>
    </div>
  </div>

  <hr>

  <div class="actions">
    <%= f.submit "Guardar", class: "btn btn-default" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<% provide(:title, "Notarios") %>
<div class="container">
  <div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
      <h2>Modificar datos de Notario</h2>

      <%= render 'form', member: @member %>
    </div>
    <div class="col-md-2">

    </div>
  </div>
</div>

app/views/members/index.html.erb
<% provide(:title, "Notarios") %>
<div class="container">
  <h2>Listado de miembros del Colegio de Notarios de Aguascalientes.</h2>
  <div class="row">
    <div class="col-md-12">
    <%= link_to 'Agregar Notario', new_member_path, class: "btn btn-default" %>
      <table>
        <thead>
          <tr>
            <th>Número</th>
            <th>Nombre</th>
            <th>Activo?</th>
            <th>Email</th>
            <th>Fecha de nacimiento</th>
            <th>Presidente?</th>
            <th>Fecha Fiat Supernumerario</th>
            <th>Fecha de Fiat Titular</th>
            <th>Fecha de asamblea de aceptación</th>
            <th>Fecha de Inicio de Ejercicio</th>
            <th>Años de servicio</th>
            <th colspan="5">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @members.each do |member| %>
            <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
              <td><%= member.numero %></td>
              <td><%= member.nombre %></td>
              <td><%= member.activo? ? "Si" : "No" %></th>
              <td><%= member.email %></td>
              <td><%= member.fechaNacimiento.to_formatted_s(:short) %></td>
              <% presi = member.presidente ? "Si" : "No" %>
              <td><%= presi %></td>
              <td><%= member.fiat_supernumerario.blank? ? '' : member.fiat_supernumerario.to_formatted_s(:db)  %></td>
              <td><%= member.fiat_notario_titular.blank? ? '' : member.fiat_notario_titular.to_formatted_s(:db)  %></td>
              <td><%= member.asamblea_aceptacion.blank? ? '' : member.asamblea_aceptacion.to_formatted_s(:db)  %></td>
              <td><%= member.inicio_ejercicio.blank? ? '' : member.inicio_ejercicio.to_formatted_s(:db)  %></td>
              <td style="text-align: center;"><%= member.inicio_ejercicio.blank? ? '' : member.total_service_time %></td>
              <td><%= link_to '', member, class: "glyphicon glyphicon-eye-open" %></td>
              <td><%= link_to '', edit_member_path(member), class: "glyphicon glyphicon-edit" %></td>
              <td><%= link_to '', member, class: "glyphicon glyphicon-trash", method: :delete, data: { confirm: '¿Está seguro?' } %></td>
              <td><%= link_to '', licenciar_path(member), class: "glyphicon glyphicon-calendar" %></td>
              <td><%= link_to '', reconocer_path(member), class: "glyphicon glyphicon-thumbs-up" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'Agregar Notario', new_member_path, class: "btn btn-default" %>
    </div>
  </div>
  <div class="form-popup" id="myForm">
  </div>
</div>

<div class="row">
    <div class="col-md-4">
      <%= form_tag import_members_path, multipart: true, class: "navbar-form navbar-left search-form" do %>
        <p>Importar archivo de Notarios en formato CSV</p>
        <%= file_field_tag :file, class: "form-control" %>
        <%= submit_tag "Importar", class: "btn btn-default" %>
      <% end %>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
      <p>Descargar:</p>
        <%= link_to members_path(format: "xls") do %>
          <%= image_tag "microsoft-excel.png", :size => '60x60' %>
        <% end %>

    </div>

</div>

app/views/members/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Número</Data></Cell>
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">e-mail</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Nacimiento</Data></Cell>
        <Cell><Data ss:Type="String">Presidencia?</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Fiat Supernumerario</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Fiat Notario Titular</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Asamblea de aceptación</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Inicio de Ejercicio</Data></Cell>
        <Cell><Data ss:Type="String">Fecha de Revocación de Fiat</Data></Cell>
        <Cell><Data ss:Type="String">Motivo de Revocación</Data></Cell>
        <Cell><Data ss:Type="String">Años de Servicio</Data></Cell>
      </Row>
    <% @members.each do |notario| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= notario.numero %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.fechaNacimiento.to_formatted_s(:short).to_s %></Data></Cell>
        <% presi = notario.presidente ? "Si" : "No" %>
        <Cell><Data ss:Type="String"><%= presi %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.fiat_supernumerario.to_formatted_s(:db).to_s %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.fiat_notario_titular.to_formatted_s(:db).to_s %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.asamblea_aceptacion.to_formatted_s(:db).to_s %></Data></Cell>
        <Cell><Data ss:Type="String"><%= notario.inicio_ejercicio.to_formatted_s(:db).to_s %></Data></Cell>
        <% if !notario.revocacion_fiat.nil? %>
          <Cell><Data ss:Type="String"><%= notario.revocacion_fiat.to_formatted_s(:db).to_s %></Data></Cell>
          <Cell><Data ss:Type="String"><%= notario.motivo_revocacion %></Data></Cell>
        <% else %>
          <Cell><Data ss:Type="String"><%= "N/A" %></Data></Cell>
          <Cell><Data ss:Type="String"><%= "N/A" %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="Number"><%= notario.total_service_time %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/members/new.html.erb
<% provide(:title, "Miembros") %>
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-sm-8">
      <h2>Agregar Notario</h2>

      <%= render 'form', member: @member %>
    </div>
    <div class="col-md-2">

    </div>
  </div>
</div>

app/views/members/show.html.erb
<% provide(:title, "Notarios") %>
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
    <h2>Datos del Notario</h2>
    <div class="col-md-6">
      <table id="vertical">
        <tr class="list_line_even">
          <td>Numero:</td>
          <td><strong><%= @member.numero %></strong></td>
        </tr>
        <tr class="list_line_odd">
          <td>Nombre:</td>
          <td><strong><%= @member.nombre %></strong></td>
        </tr>
        <tr class="list_line_even">
          <td>Activo?:</td>
          <% activo = @member.activo? ? "Si" : "No" %>
          <td><strong><%= activo %></strong></td>
        </tr>
        <tr class="list_line_odd">
          <td>Email:</td>
          <td><strong><%= @member.email %></strong></td>
        </tr>
        <tr class="list_line_even">
          <td>Fecha de nacimiento:</td>
          <td><strong><%= @member.fechaNacimiento.to_formatted_s(:short) %></strong></td>
        </tr>
        <tr class="list_line_odd">
          <td>Presidente:</td>
          <% presi = @member.presidente ? "Si" : "No" %>
          <td><strong><%= presi %></strong></td>
        </tr>
        <tr class="list_line_even">
          <td>Fecha de Fiat Supernumerario:</td>
          <% if @member.fiat_supernumerario %>
            <td><strong><%= @member.fiat_supernumerario.to_formatted_s(:db) %></strong></td>
          <% else %>
            <td>(No hay registro)</td>
          <% end %>
        </tr>
        <tr class="list_line_odd">
          <td>Fecha de Fiat Notario Titular:</td>
          <% if @member.fiat_notario_titular %>
            <td><strong><%= @member.fiat_notario_titular.to_formatted_s(:db) %></strong></td>
          <% else %>
            <td>(No hay registro)</td>
          <% end %>
        </tr>
        <tr class="list_line_even">
          <td>Fecha de Asamblea de Aceptación:</td>
          <% if @member.asamblea_aceptacion %>
            <td><strong><%= @member.asamblea_aceptacion.to_formatted_s(:db) %></strong></td>
          <% else %>
            <td>(No hay registro)</td>
          <% end %>
        </tr>
        <tr class="list_line_odd">
          <td>Fecha de Inicio de Ejercicio:</td>
          <% if @member.inicio_ejercicio %>
            <td><strong><%= @member.inicio_ejercicio.to_formatted_s(:db) %></strong></td>
          <% else %>
            <td>(No hay registro)</td>
          <% end %>
        </tr>
        <tr class="list_line_even">
          <td>Años de servicio:</td>
          <% if @member.total_service_time %>
            <td style="text-align:center;"><strong><%= @member.total_service_time %></strong></td>
          <% else %>
            <td>(No hay registro)</td>
          <% end %>
        </tr>
        <% if !@member.revocacion_fiat.nil? %>
          <tr class="list_line_odd">
            <td>Fecha de Revocación de Fiat:</td>
            <td><strong><%= @member.revocacion_fiat.to_formatted_s(:db) %></strong></td>
          </tr>
          <tr class="list_line_even">
            <td>Motivo de Revocación de Fiat:</td>
            <td><strong><%= @member.motivo_revocacion %></strong></td>
          </tr>
        <% end %>
        <tr class="last-lines">
          <td colspan="2">
            <%= link_to 'Agregar Licencias', licenciar_path(@member), class: "btn btn-in-table" %>
          </td>
        </tr>
        <tr class="last-lines">
          <td colspan="2">
            <%= link_to 'Agregar Reconocimientos', reconocer_path(@member), class: "btn btn-in-table" %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-md-6">
      <%= render '/licencias/index' %>
      <%= render '/reconocimientos/index' %>
    </div>
  </div>
  <%= link_to 'Modificar', edit_member_path(@member), class: "btn btn-default" %>
</div>
<div class="form-popup" id="myForm">
</div>